### PR TITLE
api: fix address already in use error

### LINKED ISSUE #34: Address already in use after change listen address
```yaml

roles.metrics-export:
  http:
  - listen: '127.0.0.1:8080' # change to '0.0.0.0:8080' and apply   `require('config'):reload()`
    endpoints:
    - path: /metrics/prometheus
      format: prometheus
    - path: /metrics/json
      format: json   

```

result : 

```yaml 

---
- error: 'Error applying role roles.metrics-export: /opt/tarantool/.rocks/share/tarantool/http/server.lua:1363:
    Can''t create tcp_server: Address already in use'
...

```

### PR DESCRIPTION
**Pull request by themilchenko**
There was a bug when user wants to change server's `listen` address and reload config on the fly - error `address already in use` occures.

This patch reworks server's address handling by applying roles' config.

Closes #34

### CODE REVIEW

File: roles/metrics-export.lua [hunk 1]
```diff
@@ -339,23 +339,33 @@ local function apply_http(conf)
...
             -- Since the 'listen' and 'server' names of other servers in the config may be
-            -- the same, we create a unique string concatenating the key name and information
-            -- about whether it is an httpd key or not.
-            enabled[tostring(target.value) .. tostring(target.is_httpd_role)] = true
+            -- the same, we create a unique string concatenating the host and port of a server.
+            enabled[target.value] = true
+
+            if http_servers[target.value] == nil then
+                if target.httpd_name == nil then
+                    for k in pairs(http_servers) do
```
Comment (DerekBum) [inline roles/metrics-export.lua]: Do we need to add `or {}` here also? Like its done in line 431.

File: test/integration/reload_config_test.lua [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+    helpers.skip_if_unsupported()
+end)
+
+g.before_each(function(cg)
+    cg.workdir = fio.tempdir()
+    fio.mktree(cg.workdir)
+
+    fio.copytree(".rocks", fio.pathjoin(cg.workdir, ".rocks"))
+    fio.copytree("roles", fio.pathjoin(cg.workdir, "roles"))
+    fio.copytree(fio.pathjoin("test", "ssl_data"), fio.pathjoin(cg.workdir, "ssl_data"))
```
Comment (DerekBum) [inline test/integration/reload_config_test.lua:20]: Do we need ssl files in this test?

File: roles/metrics-export.lua (hunk 1 above)
Comment (themilchenko) [reply roles/metrics-export.lua]: It was already set a few lines above:

https://github.com/tarantool/metrics-export-role/blob/7d6db3b7e3c931c96dd7ad3730730b53f27b4b0a/roles/metrics-export.lua#L351

File: test/integration/reload_config_test.lua (hunk 2 above)
Comment (themilchenko) [reply test/integration/reload_config_test.lua:20]: Since testing config in `test/entrypoint/config.yaml` has paths to ssl files, we need to copy them too. I don't know what will be better: left as it is now or add one more testing config with the only testing endpoint to remove copying of extra ssl files.

File: roles/metrics-export.lua [hunk 3]
```diff
@@ -339,23 +339,49 @@ local function apply_http(conf)
...
+                    local count_global_addrs = 0
+
+                    for _, n in pairs(conf) do
+                        -- Count if it is more than one server that on gloabl address 0.0.0.0.
+                        if n.listen ~= nil and string.find(tostring(n.listen), tostring(port)) ~= nil then
+                            count_global_addrs = count_global_addrs + 1
+                        end
+                    end
+
+                    if host == '0.0.0.0' then
```
Comment (DifferentialOrange) [inline roles/metrics-export.lua]: So what's with `0.0.0.0` processing here? I've thought that the plan was rather straightforward.

### Case 1

Before
```
name: server_x
listen: 0.0.0.0:8081
```

After
```
name: server_x
listen: 0.0.0.0:8081
```

Do not do anything, since `"server_x" == "server_x" and "0.0.0.0:8081" == "0.0.0.0:8081"`.

### Case 2

Before
```
name: server_x
listen: 0.0.0.0:8081
```

After
```
name: server_x
listen: 0.0.0.0:8081


name: server_y
listen: 0.0.0.0:8082
```

Do not do anything with server_x (see case 1), start server_y.

### Case 3

Before
```
name: server_x
listen: 0.0.0.0:8081
```

After
```
name: server_x
listen: 0.0.0.0:8082
```

Drop existing server_x, start new server_x, since `"0.0.0.0:8081" != "0.0.0.0:8082"`.

### Case 4

Before
```
name: server_x
listen: 0.0.0.0:8081
```

After
```
name: server_x
listen: 127.0.0.1:8081
```

Drop existing server_x, start new server_x, since `"0.0.0.0:8081" != "127.0.0.1:8081"` and validating whether `127.0.0.1` is exactly `0.0.0.0` or not on this machine is complicated (and server restart should be fine, since no one is expected to change the hostname often).

### Case 5

Before
```
name: server_x
listen: 0.0.0.0:8081
```

After
```
name: server_y
listen: 0.0.0.0:8081
```

Drop server_x, start server_y, since `"server_x" != "server_y"`.

### Case 6

Before
```
name: server_x
listen: 0.0.0.0:8081
```

After
```
name: server_y
listen: localhost:8082
```


Drop server_x, start server_y, since `"server_x" != "server_y"` or `"0.0.0.0:8081" != "localhost:8082"`.

### Case 7

Before
```
name: server_x
listen: 0.0.0.0:8081
```

After
```
```


Drop server_x.

File: roles/metrics-export.lua [hunk 4]
```diff
@@ -339,23 +339,49 @@ local function apply_http(conf)
...
+                            for k in pairs(http_servers) do
+                                if http_servers[k].httpd_name == nil and string.find(k, ':' .. port) ~= nil then
+                                    http_servers[k].httpd:stop()
+                                    enabled[k] = false
+                                end
+                            end
+                        end
+                    elseif http_servers['listen_0.0.0.0:' .. port] ~= nil and count_global_addrs == 1 then
+                        local key = 'listen_0.0.0.0:' .. port
+                        http_servers[key].httpd:stop()
```
Comment (DifferentialOrange) [inline roles/metrics-export.lua]: On the other hand, we should think whether roles using httpd role servers (like tcf ones) are prepared for server reload and make some changes (together with documentation tips here), if not.

File: roles/metrics-export.lua [hunk 5]
```diff
@@ -339,23 +339,49 @@ local function apply_http(conf)
...
+                    if host == '0.0.0.0' then
+                        if count_global_addrs == 1 then
+                            for k in pairs(http_servers) do
+                                if http_servers[k].httpd_name == nil and string.find(k, ':' .. port) ~= nil then
+                                    http_servers[k].httpd:stop()
+                                    enabled[k] = false
+                                end
+                            end
+                        end
+                    elseif http_servers['listen_0.0.0.0:' .. port] ~= nil and count_global_addrs == 1 then
```
Comment (DifferentialOrange) [inline roles/metrics-export.lua]: By the way, it seems that we will update something here and then copypaste it to `httpd`? It seems like the time to make a part of `httpd` a "library" and borrow the code from it, if it's not too time-consuming.

File: roles/metrics-export.lua (hunk 3 above)
Comment (themilchenko) [reply roles/metrics-export.lua]: > So what's with `0.0.0.0` processing here? I've thought that the plan was rather straightforward.

The processing of `0.0.0.0` is handled a little differently from others addresses since `0.0.0.0` means to listen from all interfaces.

So in my implementation, we check that there is only one `0.0.0.0` with corresponding port:

https://github.com/tarantool/metrics-export-role/blob/66281f8f18f005c66d9cf8b645ebbd7ea2e9c3dd/roles/metrics-export.lua#L360-L367

 If so, we stop current servers to not trigger an error `address already in use`:

https://github.com/tarantool/metrics-export-role/blob/66281f8f18f005c66d9cf8b645ebbd7ea2e9c3dd/roles/metrics-export.lua#L370-L377

Otherwise, when we want to replace `0.0.0.0` on something different with its port, we stop it for same reason:

https://github.com/tarantool/metrics-export-role/blob/66281f8f18f005c66d9cf8b645ebbd7ea2e9c3dd/roles/metrics-export.lua#L378-L383

File: roles/metrics-export.lua (hunk 5 above)
Comment (themilchenko) [reply roles/metrics-export.lua]: I think it should be done in a separate task.

File: roles/metrics-export.lua (hunk 3 above)
Comment (DifferentialOrange) [reply roles/metrics-export.lua]: > If so, we stop current servers to not trigger an error address already in use:

If one configures `http` to have both `0.0.0.0:8081` and `127.0.0.1:8081`, I think it's expected to fail with address already in use error.

Comment (themilchenko) [reply roles/metrics-export.lua]: > > If so, we stop current servers to not trigger an error address already in use:
> 
> If one configures `http` to have both `0.0.0.0:8081` and `127.0.0.1:8081`, I think it's expected to fail with address already in use error.

No, I mean case when user wants to replace `127.0.0.1:8081` on `0.0.0.0:8081`.

**Comment by themilchenko** [comment]
I have fixed things we talked before. Now we search for unused servers on each apply and stop it before creating and editing new ones.

PR is ready for the next review.

File: roles/metrics-export.lua [hunk 6]
```diff
@@ -322,15 +322,67 @@ local function routes_equal(old, new)
...
+    end
+end
+
 local function apply_http(conf)
-    local enabled = {}
+    -- Stop old servers.
+    for name in pairs(http_servers or {}) do
+        local server_found = false
+
+        for _, node in pairs(conf) do
```
Comment (DifferentialOrange) [inline roles/metrics-export.lua]: Even though this isn't likely to be a performance bottleneck, let's parse everything in a single loop and only check whether server is found in a nested loop.

File: roles/metrics-export.lua [hunk 7]
```diff
@@ -322,15 +322,67 @@ local function routes_equal(old, new)
...
+                    key = 'httpd_' .. httpd_role.DEFAULT_SERVER_NAME
+                end
+
+                if name == key then
+                    server_found = true
+                    break
+                end
+            end
+        end
+
```
Comment (DifferentialOrange) [inline roles/metrics-export.lua]: Extra newline

File: roles/metrics-export.lua [hunk 8]
```diff
@@ -322,15 +322,67 @@ local function routes_equal(old, new)
...
+                if node.server ~= nil then
+                    key = 'httpd_' .. node.server
+                elseif node.listen ~= nil then
+                    local host, port, err = parse_listen(node.listen)
+                    if err ~= nil then
+                        error("failed to parse URI: " .. err, 2)
+                    end
+
+                    key = 'listen_' .. host .. ':' .. tostring(port)
```
Comment (DifferentialOrange) [inline roles/metrics-export.lua]: Shouldn't we work only with `listen` servers, since metrics-export-role don't start named ones itself?

File: roles/metrics-export.lua (hunk 6 above)
Comment (themilchenko) [reply roles/metrics-export.lua]: Reworked.

File: roles/metrics-export.lua (hunk 7 above)
Comment (themilchenko) [reply roles/metrics-export.lua]: Deleted.

File: roles/metrics-export.lua (hunk 8 above)
Comment (themilchenko) [reply roles/metrics-export.lua]: Yes, took that into account.

File: roles/metrics-export.lua [hunk 9]
```diff
@@ -322,15 +322,35 @@ local function routes_equal(old, new)
     return true
 end
 
+local function stop_server(name)
```
Comment (DifferentialOrange) [inline roles/metrics-export.lua]: Sounds more like "disable_server"

**Review by DifferentialOrange — APPROVED** [review]

File: roles/metrics-export.lua (hunk 9 above)
Comment (themilchenko) [reply roles/metrics-export.lua]: Renamed, thanks.

**Review by DifferentialOrange — APPROVED** [review]

File: test/unit/http_test.lua [hunk 10]
```diff
@@ -858,6 +909,61 @@ local test_reapply_add_cases = {
...
+                        },
+                    },
+                },
+                expected_json_urls = {},
+                expected_prometheus_urls = {
+                    "http://127.0.0.1:8081/metrics1"
+                },
+                expected_none_urls = {
+                    "http://127.0.0.1:8081/metrics2",
+                    "http://127.0.0.1:8082/metrics/1",
```
Comment (DerekBum) [inline test/unit/http_test.lua]:
```suggestion
                    "http://127.0.0.1:8082/metrics1",
```

**Review by DerekBum — APPROVED** [review]

File: test/unit/http_test.lua (hunk 10 above)
Comment (themilchenko) [reply test/unit/http_test.lua]: `expected_none_urls` is about testing routes which are not available.

Comment (DerekBum) [reply test/unit/http_test.lua]: But is it supposed to be `/metrics/1`?  `http://127.0.0.1:8082/metrics1` also doesnt exist, does it?

Comment (themilchenko) [reply test/unit/http_test.lua]: It doesn't matter because non of them exist, but to be symmetrical changed path on suggested one.
